// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { ListGroupInUse, ListItem } from '../../components/DataDisplay';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Data Display/List Item",
  component: ListItem,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "Trailing": {
    "control": "select",
    "options": [
      "Chevron",
      "Value",
      "Toggle",
      "Checkbox",
      "None"
    ],
    "description": "Figma variant property `Trailing`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Chevron"
      }
    }
  },
  "Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Title"
      }
    }
  },
  "Supporting Text": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Supporting text"
      }
    }
  },
  "Show Supporting Text": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Value": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "English"
      }
    }
  },
  "Leading Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Leading Icon Swap": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Settings"
      }
    }
  },
  "Show Separator": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Trailing": "Chevron", "Title": "Title", "Supporting Text": "Supporting text", "Show Supporting Text": false, "Value": "English", "Leading Icon": true, "Leading Icon Swap": "Icon/Settings", "Show Separator": true},
  parameters: {
    figma: { name: "List Item", page: "➜ List Item", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-28375" },
    docs: { description: { component: "**Figma:** `List Item` on page `➜ List Item` (Data Display). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-28375)\n\n**Tier:** Molecule\n\n**Use:** One row in a list or settings group: navigates (Chevron, Value), toggles a setting (Toggle) or selects (Checkbox).\n\n**Figma description:**\n\n> Purpose: One row in a list or settings group: navigates (Chevron, Value), toggles a setting (Toggle) or selects (Checkbox).  \n> Usage Rules: Stack rows in a group with no gap; turn Show Separator off on the last row of a group. Chevron/Value rows open a new screen (chevron shows on iOS only, Android uses the whole row). Toggle rows apply at once. Title 1 line, Supporting Text up to 2 lines. In RTL the row mirrors automatically; the exposed Toggle/Checkbox exist once per direction (set both when overriding).  \n> Accessibility: Whole row is the touch target (44 iOS / 56 Android). Toggle and Checkbox take their label from Title. Title Label/Primary, supporting and value text Label/Secondary (4.5:1+).  \n\n**Built from:** `Icon/Settings`, `Icon/Chevron Right`, `Toggle`, `Checkbox`, `Icon/Check`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof ListItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Chevron: Story = { name: "Chevron", args: { "Trailing": "Chevron" } };
export const Value: Story = { name: "Value", args: { "Trailing": "Value" } };
export const Toggle: Story = { name: "Toggle", args: { "Trailing": "Toggle" } };
export const Checkbox: Story = { name: "Checkbox", args: { "Trailing": "Checkbox" } };
export const None: Story = { name: "None", args: { "Trailing": "None" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Chevron", "Value", "Toggle", "Checkbox", "None"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Trailing={x}</div>
          <ListItem {...args} {...{ "Trailing": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const InUse: Story = { name: 'In use (interactive)', render: () => <ListGroupInUse /> };
