// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { SettingsScreen } from '../../components/Patterns';

const meta = {
  title: "Patterns/Pattern/Settings Screen",
  component: SettingsScreen,
  tags: ['!autodocs', 'tier-pattern'],
  argTypes: {},
  args: {},
  parameters: {
    figma: { name: "Pattern/Settings Screen", page: "➜ Settings", tier: "Pattern", order: 4 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-28729" },
    docs: { description: { component: "**Figma:** `Pattern/Settings Screen` on page `➜ Settings` (Patterns). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-28729)\n\n**Tier:** Pattern\n\n**Use:** Reference Settings screen for the one-file native method: the same screen renders as iOS or Android through the OS mode.\n\n**Figma description:**\n\n> Purpose: Reference Settings screen for the one-file native method: the same screen renders as iOS or Android through the OS mode.  \n> Usage Rules: Build screens from DS instances only. Set OS, Color and Language modes on the screen frame; never detach to fake a platform.  \n> Accessibility: Touch targets and contrast come from the components.  \n\n**Built from:** `Top App Bar`, `_Top App Bar Platform`, `Icon/Back`, `Icon Button`, `Icon/Settings`, `Text Field`, `Icon/Person`, `Icon/Close`, `Segmented Control`, `Segment`, `Icon/Check`, `List Item`, `Icon/Notifications`, `Toggle`, `Icon/Moon`, `Icon/Globe`, `Icon/Chevron Right`, `Icon/Lock`, `Button`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof SettingsScreen>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
