// One-time migration: drop duplicates created before the rename, then rename OS component tokens to Components/... (keeps ids and bindings).
const R = {"Height/Button": "Components/Button/Height", "Radius/Button": "Components/Button/Radius", "Spacing/Button Padding X": "Components/Button/Padding X", "Height/Icon Button": "Components/Icon Button/Size", "Size/Icon": "Components/Icon/Size", "Height/List Item": "Components/List Item/Min Height", "Spacing/List Item Padding X": "Components/List Item/Padding X", "Spacing/List Item Padding Y": "Components/List Item/Padding Y", "Surface/List": "Components/List Item/Fill", "Spacing/List Inset": "Components/List Group/Inset", "Radius/List Group": "Components/List Group/Radius", "Height/Text Field": "Components/Text Field/Height", "Radius/Field": "Components/Text Field/Radius", "Spacing/Field Padding X": "Components/Text Field/Padding X", "Spacing/Label Padding": "Components/Text Field/Label Padding", "Height/Top Bar": "Components/Top App Bar/Height", "Spacing/Bar Padding X": "Components/Top App Bar/Padding X", "Spacing/Bar Title Inset": "Components/Top App Bar/Title Inset", "Surface/Top Bar": "Components/Top App Bar/Fill", "Segmented Control/Radius Outer": "Components/Segmented Control/Radius Outer", "Segmented Control/Radius Inner": "Components/Segmented Control/Radius Inner", "Segmented Control/Height": "Components/Segmented Control/Height", "Segmented Control/Padding": "Components/Segmented Control/Padding", "Toggle/Track Width": "Components/Toggle/Track Width", "Toggle/Track Height": "Components/Toggle/Track Height", "Toggle/Thumb Size Off": "Components/Toggle/Thumb Size Off", "Toggle/Thumb Size On": "Components/Toggle/Thumb Size On", "Toggle/Track Border": "Components/Toggle/Track Border", "Toggle/Thumb Inset Off": "Components/Toggle/Thumb Inset Off", "Toggle/Thumb Inset On": "Components/Toggle/Thumb Inset On", "Segmented Control/Border": "Components/Segmented Control/Border", "Checkbox/Glyph": "Components/Checkbox/Glyph", "Checkbox/Size": "Components/Checkbox/Size", "Checkbox/Radius": "Components/Checkbox/Radius", "Toggle/Thumb Off": "Components/Toggle/Thumb Off", "Toggle/Track Border Color": "Components/Toggle/Track Border Color", "Checkbox/Border": "Components/Checkbox/Border", "Text Field/Border": "Components/Text Field/Border", "Text Field/Border Focused": "Components/Text Field/Border Focused", "Toggle/Thumb On": "Components/Toggle/Thumb On", "Segmented Control/Track": "Components/Segmented Control/Track", "Segmented Control/Selected Fill": "Components/Segmented Control/Selected Fill", "Text Field/Fill": "Components/Text Field/Fill"};
const os = (await figma.variables.getLocalVariableCollectionsAsync()).find(c => c.name === 'OS');
const vs = (await figma.variables.getLocalVariablesAsync()).filter(v => v.variableCollectionId === os.id);
const targets = new Set(Object.values(R)); let del = 0, n = 0;
const olds = vs.filter(v => R[v.name]);
for (const v of vs) if (targets.has(v.name) && olds.length) { v.remove(); del++; }
for (const v of olds) { v.name = R[v.name]; n++; }
return { deleted: del, renamed: n };
