// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Button } from '../../components/Navigation';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Navigation/Button",
  component: Button,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Variant": {
    "control": "inline-radio",
    "options": [
      "Primary",
      "Secondary",
      "Text"
    ],
    "description": "Figma variant property `Variant`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Primary"
      }
    }
  },
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Pressed",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Button"
      }
    }
  },
  "Leading Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Check"
      }
    }
  }
},
  args: {"Variant": "Primary", "State": "Default", "Label": "Button", "Leading Icon": false, "Icon": "Icon/Check"},
  parameters: {
    figma: { name: "Button", page: "➜ Button", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-27861" },
    docs: { description: { component: "**Figma:** `Button` on page `➜ Button` (Navigation). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-27861)\n\n**Tier:** Atom\n\n**Use:** Main action on a screen (Primary), alternative actions (Secondary), low emphasis or inline actions (Text).\n\n**Figma description:**\n\n> Purpose: Main action on a screen (Primary), alternative actions (Secondary), low emphasis or inline actions (Text).  \n> Usage Rules: One Primary per screen. Label is a verb, sentence case, 1-3 words. Leading Icon only when it adds meaning. Use Text for actions in bars and dialogs. Platform look (height, radius, label style) comes from the OS mode, never from a separate component.  \n> Accessibility: Touch target at least 44x44 (iOS) / 48x48 (Android): the 40px Android button needs 4px extra hit area. Primary label on the yellow fill uses Label/On Accent (14.7:1); Text label uses Label/Accent (4.7:1 on white). Disabled is not announced as actionable.  \n\n**Built from:** `Icon/Check`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Primary: Story = { name: "Primary", args: { "Variant": "Primary" } };
export const Secondary: Story = { name: "Secondary", args: { "Variant": "Secondary" } };
export const Text: Story = { name: "Text", args: { "Variant": "Text" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StatePressed: Story = { name: "State=Pressed", args: { "State": "Pressed" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Pressed", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Button {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const Icons: Story = {
  name: 'Icons',
  render: (args) => (
    <div className="sb-row">
      {[["Leading Icon", {"Leading Icon": true}]].map(([label, extra]: any) => (
        <div key={label}>
          <div className="sb-cell-label ts-xs-medium">{label}</div>
          <Button {...args} {...extra} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Primary", "Secondary", "Text"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Variant={x}</div>
          <div className="sb-row">{["Default", "Pressed", "Disabled"].map((y) => <Button key={y} {...args} {...{ "Variant": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
