// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { IconButton } from '../../components/Navigation';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Navigation/Icon Button",
  component: IconButton,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Variant": {
    "control": "inline-radio",
    "options": [
      "Standard",
      "Filled"
    ],
    "description": "Figma variant property `Variant`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Standard"
      }
    }
  },
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Pressed",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Settings"
      }
    }
  }
},
  args: {"Variant": "Standard", "State": "Default", "Icon": "Icon/Settings"},
  parameters: {
    figma: { name: "Icon Button", page: "➜ Icon Button", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=4-15444" },
    docs: { description: { component: "**Figma:** `Icon Button` on page `➜ Icon Button` (Navigation). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=4-15444)\n\n**Tier:** Atom\n\n**Use:** Compact action shown only as an icon (toolbar and top bar actions, close, search).\n\n**Figma description:**\n\n> Purpose: Compact action shown only as an icon (toolbar and top bar actions, close, search).  \n> Usage Rules: Use only for icons whose meaning is universal (search, close, settings, back); otherwise use Button with a label. Standard in bars, Filled for one prominent floating action. Swap the icon through the Icon property, never detach.  \n> Accessibility: Size equals the platform touch target (44 iOS / 48 Android). Needs an accessibility label in code (the icon has no text). Disabled uses State/Disabled Opacity (0.4 iOS / 0.38 Android).  \n\n**Built from:** `Icon/Settings`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof IconButton>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Standard: Story = { name: "Standard", args: { "Variant": "Standard" } };
export const Filled: Story = { name: "Filled", args: { "Variant": "Filled" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StatePressed: Story = { name: "State=Pressed", args: { "State": "Pressed" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Pressed", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <IconButton {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Standard", "Filled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Variant={x}</div>
          <div className="sb-row">{["Default", "Pressed", "Disabled"].map((y) => <IconButton key={y} {...args} {...{ "Variant": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
