// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Segment } from '../../components/Navigation';

const meta = {
  title: "Navigation/Segment",
  component: Segment,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Selected": {
    "control": "inline-radio",
    "options": [
      "Yes",
      "No"
    ],
    "description": "Figma variant property `Selected`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Yes"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Segment"
      }
    }
  }
},
  args: {"Selected": "Yes", "Label": "Segment"},
  parameters: {
    figma: { name: "Segment", page: "➜ Segmented Control", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-27895" },
    docs: { description: { component: "**Figma:** `Segment` on page `➜ Segmented Control` (Navigation). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-27895)\n\n**Tier:** Atom\n\n**Use:** One option inside a Segmented Control. Not used on its own.\n\n**Figma description:**\n\n> Purpose: One option inside a Segmented Control. Not used on its own.  \n> Usage Rules: Only inside Segmented Control. Label 1-2 words, no icons except the Android selected check (automatic).  \n> Accessibility: Selected state is not color-only: iOS adds a raised pill, Android adds a check icon.  \n\n**Built from:** `Icon/Check`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof Segment>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Yes: Story = { name: "Yes", args: { "Selected": "Yes" } };
export const No: Story = { name: "No", args: { "Selected": "No" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Yes", "No"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Selected={x}</div>
          <Segment {...args} {...{ "Selected": x } as any} />
        </div>
      ))}
    </div>
  ),
};
