// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { SegmentedControl, SegmentedControlInUse } from '../../components/Navigation';

const meta = {
  title: "Navigation/Segmented Control",
  component: SegmentedControl,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "Show Segment 4": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Show Segment 3": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Show Segment 4": false, "Show Segment 3": true},
  parameters: {
    figma: { name: "Segmented Control", page: "➜ Segmented Control", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-27896" },
    docs: { description: { component: "**Figma:** `Segmented Control` on page `➜ Segmented Control` (Navigation). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-27896)\n\n**Tier:** Molecule\n\n**Use:** Switches between 2-4 views or filters of the same content.\n\n**Figma description:**\n\n> Purpose: Switches between 2-4 views or filters of the same content.  \n> Usage Rules: Use 2-4 segments with short labels of similar length; more options -> Tabs or Select. Exactly one segment selected (set Selected on the exposed Segment). Not for actions (use Button) or settings (use Toggle).  \n> Accessibility: Each segment is at least 44 (iOS: 32 control + list padding) / 48 Android touch target in context. Selected state uses shape and icon, not only color. Labels via the exposed Segment Label properties.  \n\n**Built from:** `Segment`, `Icon/Check`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof SegmentedControl>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};

export const InUse: Story = { name: 'In use (interactive)', render: () => <SegmentedControlInUse /> };
