// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { TopAppBar } from '../../components/Navigation';

const meta = {
  title: "Navigation/Top App Bar",
  component: TopAppBar,
  tags: ['!autodocs', 'tier-organism'],
  argTypes: {
  "Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Title"
      }
    }
  },
  "Show Back": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Back Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Back"
      }
    }
  },
  "Show Action": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Large Title": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Show Inline Title": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Title": "Title", "Show Back": true, "Back Label": "Back", "Show Action": true, "Large Title": false, "Show Inline Title": true},
  parameters: {
    figma: { name: "Top App Bar", page: "➜ Top App Bar", tier: "Organism", order: 3 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-28483" },
    docs: { description: { component: "**Figma:** `Top App Bar` on page `➜ Top App Bar` (Navigation). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-28483)\n\n**Tier:** Organism\n\n**Use:** Top of every screen: title, back navigation and up to one action.\n\n**Figma description:**\n\n> Purpose: Top of every screen: title, back navigation and up to one action.  \n> Usage Rules: Always use this wrapper (never the private set). Platform anatomy comes from the OS mode: iOS centered title with text back button and optional Large Title; Android left title with back arrow. Title 1-3 words. Show Action only for the screen's main secondary action.  \n> Accessibility: Back and Action targets are 44 iOS / 48 Android. Title uses Headline (iOS) / Title Large (Android) on Surface/Top Bar (contrast 15:1+). Back Label is announced as \"Back\" on iOS.  \n\n**Built from:** `_Top App Bar Platform`, `Icon/Back`, `Icon Button`, `Icon/Settings`\n\n**Known Figma gaps (see gaps.md):** Properties are exposed from the nested private set _Top App Bar Platform; its Platform variant is bound to OS::Platform/Name.\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof TopAppBar>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
