// DesignTokens.kt - Native One File Pilot design tokens for Jetpack Compose (OS mode: Android).
// Generated by tools/tokens_to_css.py from data/tokens.json (Figma variables). Do not edit by hand.
// Names in Storybook are the Figma Code syntax; the objects below declare the ones that are app tokens
// (Spacing.ScreenMargin, Size.Icon...). Material 3 APIs (MaterialTheme.colorScheme.surface, ButtonDefaults...) are
// used as they are; AppColors holds this design system's own values for each Color mode.
package designsystem.native_one_file_pilot

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Immutable
data class AppColors(
    val backgroundPrimary: Color, // Color::Background/Primary · Figma: MaterialTheme.colorScheme.surface
    val backgroundGrouped: Color, // Color::Background/Grouped · Figma: MaterialTheme.colorScheme.surfaceContainerLowest
    val backgroundElevated: Color, // Color::Background/Elevated · Figma: MaterialTheme.colorScheme.surfaceContainerLow
    val surfaceContainer: Color, // Color::Surface/Container · Figma: MaterialTheme.colorScheme.surfaceContainer
    val surfaceContainerHigh: Color, // Color::Surface/Container High · Figma: MaterialTheme.colorScheme.surfaceContainerHigh
    val labelPrimary: Color, // Color::Label/Primary · Figma: MaterialTheme.colorScheme.onSurface
    val labelSecondary: Color, // Color::Label/Secondary · Figma: MaterialTheme.colorScheme.onSurfaceVariant
    val labelTertiary: Color, // Color::Label/Tertiary · Figma: MaterialTheme.colorScheme.outline
    val labelDisabled: Color, // Color::Label/Disabled · Figma: MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f)
    val labelOnAccent: Color, // Color::Label/On Accent · Figma: MaterialTheme.colorScheme.onPrimary
    val labelAccent: Color, // Color::Label/Accent · Figma: MaterialTheme.colorScheme.primary
    val labelError: Color, // Color::Label/Error · Figma: MaterialTheme.colorScheme.error
    val fillAccent: Color, // Color::Fill/Accent · Figma: MaterialTheme.colorScheme.primaryContainer
    val fillAccentPressed: Color, // Color::Fill/Accent Pressed · Figma: MaterialTheme.colorScheme.primaryContainer
    val fillSecondary: Color, // Color::Fill/Secondary · Figma: MaterialTheme.colorScheme.secondaryContainer
    val fillSecondaryPressed: Color, // Color::Fill/Secondary Pressed · Figma: MaterialTheme.colorScheme.secondaryContainer
    val fillDisabled: Color, // Color::Fill/Disabled · Figma: MaterialTheme.colorScheme.onSurface.copy(alpha = 0.12f)
    val fillTrackOff: Color, // Color::Fill/Track Off · Figma: MaterialTheme.colorScheme.surfaceContainerHighest
    val fillThumb: Color, // Color::Fill/Thumb · Figma: MaterialTheme.colorScheme.onPrimary
    val fillThumbOff: Color, // Color::Fill/Thumb Off · Figma: MaterialTheme.colorScheme.outline
    val fillSegmentSelected: Color, // Color::Fill/Segment Selected · Figma: MaterialTheme.colorScheme.secondaryContainer
    val iconPrimary: Color, // Color::Icon/Primary · Figma: MaterialTheme.colorScheme.onSurface
    val iconSecondary: Color, // Color::Icon/Secondary · Figma: MaterialTheme.colorScheme.onSurfaceVariant
    val iconAccent: Color, // Color::Icon/Accent · Figma: MaterialTheme.colorScheme.primary
    val iconOnAccent: Color, // Color::Icon/On Accent · Figma: MaterialTheme.colorScheme.onPrimaryContainer
    val iconDisabled: Color, // Color::Icon/Disabled · Figma: MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f)
    val borderDefault: Color, // Color::Border/Default · Figma: MaterialTheme.colorScheme.outlineVariant
    val borderStrong: Color, // Color::Border/Strong · Figma: MaterialTheme.colorScheme.outline
    val borderFocus: Color, // Color::Border/Focus · Figma: MaterialTheme.colorScheme.primary
    val borderError: Color, // Color::Border/Error · Figma: MaterialTheme.colorScheme.error
    val separatorDefault: Color, // Color::Separator/Default · Figma: MaterialTheme.colorScheme.outlineVariant
    val shadowDefault: Color, // Color::Shadow/Default · Figma: MaterialTheme.colorScheme.shadow
    val shadowNone: Color, // Color::Shadow/None · Figma: Color.Transparent
    val surfaceScreen: Color, // OS::Surface/Screen · Figma: MaterialTheme.colorScheme.surface
    val shadowElevation1: Color, // OS::Shadow/Elevation 1 · Figma: MaterialTheme.colorScheme.shadow
    val fillOnAccent: Color, // Color::Fill/On Accent · Figma: MaterialTheme.colorScheme.onPrimaryContainer
    val fillAccentSubtle: Color, // Color::Fill/Accent Subtle · Figma: MaterialTheme.colorScheme.secondaryContainer
    val fillTransparent: Color, // Color::Fill/Transparent · Figma: Color.Transparent
    val componentSpecificListItemFill: Color, // Component Specific::List Item/Fill · Figma: MaterialTheme.colorScheme.surface
    val componentSpecificTopAppBarFill: Color, // Component Specific::Top App Bar/Fill · Figma: MaterialTheme.colorScheme.surface
    val componentSpecificToggleThumbOff: Color, // Component Specific::Toggle/Thumb Off · Figma: MaterialTheme.colorScheme.outline
    val componentSpecificToggleTrackBorderColor: Color, // Component Specific::Toggle/Track Border Color · Figma: MaterialTheme.colorScheme.outline
    val componentSpecificToggleThumbOn: Color, // Component Specific::Toggle/Thumb On · Figma: MaterialTheme.colorScheme.onPrimaryContainer
    val componentSpecificSegmentedControlTrack: Color, // Component Specific::Segmented Control/Track · Figma: Color.Transparent
    val componentSpecificSegmentedControlSelectedFill: Color, // Component Specific::Segmented Control/Selected Fill · Figma: MaterialTheme.colorScheme.secondaryContainer
    val componentSpecificTextFieldFill: Color, // Component Specific::Text Field/Fill · Figma: Color.Transparent
)

val LightAppColors = AppColors(
    backgroundPrimary = Color(0xFFFFFFFF),
    backgroundGrouped = Color(0xFFF2F2F7),
    backgroundElevated = Color(0xFFFFFFFF),
    surfaceContainer = Color(0xFFF2F2F7),
    surfaceContainerHigh = Color(0xFFE5E5EA),
    labelPrimary = Color(0xFF000000),
    labelSecondary = Color(0xFF636366),
    labelTertiary = Color(0xFF8E8E93),
    labelDisabled = Color(0xFFC7C7CC),
    labelOnAccent = Color(0xFF111113),
    labelAccent = Color(0xFFA36600),
    labelError = Color(0xFFB91C1C),
    fillAccent = Color(0xFFFDD501),
    fillAccentPressed = Color(0xFFECBB00),
    fillSecondary = Color(0xFFE5E5EA),
    fillSecondaryPressed = Color(0xFFD1D1D6),
    fillDisabled = Color(0xFFE5E5EA),
    fillTrackOff = Color(0xFFE5E5EA),
    fillThumb = Color(0xFFFFFFFF),
    fillThumbOff = Color(0xFF8E8E93),
    fillSegmentSelected = Color(0xFFFFFFFF),
    iconPrimary = Color(0xFF000000),
    iconSecondary = Color(0xFF8E8E93),
    iconAccent = Color(0xFFA36600),
    iconOnAccent = Color(0xFF111113),
    iconDisabled = Color(0xFFC7C7CC),
    borderDefault = Color(0xFFD1D1D6),
    borderStrong = Color(0xFF8E8E93),
    borderFocus = Color(0xFFA36600),
    borderError = Color(0xFFDC2626),
    separatorDefault = Color(0xFFD1D1D6),
    shadowDefault = Color(0x33000000),
    shadowNone = Color(0x00000000),
    surfaceScreen = Color(0xFFFFFFFF),
    shadowElevation1 = Color(0x33000000),
    fillOnAccent = Color(0xFF111113),
    fillAccentSubtle = Color(0xFFFDFCC3),
    fillTransparent = Color(0x00000000),
    componentSpecificListItemFill = Color(0xFFFFFFFF),
    componentSpecificTopAppBarFill = Color(0xFFFFFFFF),
    componentSpecificToggleThumbOff = Color(0xFF8E8E93),
    componentSpecificToggleTrackBorderColor = Color(0xFF8E8E93),
    componentSpecificToggleThumbOn = Color(0xFF111113),
    componentSpecificSegmentedControlTrack = Color(0x00000000),
    componentSpecificSegmentedControlSelectedFill = Color(0xFFFDFCC3),
    componentSpecificTextFieldFill = Color(0x00000000),
)

val DarkAppColors = AppColors(
    backgroundPrimary = Color(0xFF000000),
    backgroundGrouped = Color(0xFF000000),
    backgroundElevated = Color(0xFF1C1C1E),
    surfaceContainer = Color(0xFF1C1C1E),
    surfaceContainerHigh = Color(0xFF2C2C2E),
    labelPrimary = Color(0xFFFFFFFF),
    labelSecondary = Color(0xFFAEAEB2),
    labelTertiary = Color(0xFF8E8E93),
    labelDisabled = Color(0xFF48484A),
    labelOnAccent = Color(0xFF111113),
    labelAccent = Color(0xFFFDD501),
    labelError = Color(0xFFF87171),
    fillAccent = Color(0xFFFDD501),
    fillAccentPressed = Color(0xFFFDE744),
    fillSecondary = Color(0xFF2C2C2E),
    fillSecondaryPressed = Color(0xFF3A3A3C),
    fillDisabled = Color(0xFF2C2C2E),
    fillTrackOff = Color(0xFF3A3A3C),
    fillThumb = Color(0xFFFFFFFF),
    fillThumbOff = Color(0xFF8E8E93),
    fillSegmentSelected = Color(0xFF48484A),
    iconPrimary = Color(0xFFFFFFFF),
    iconSecondary = Color(0xFF8E8E93),
    iconAccent = Color(0xFFFDD501),
    iconOnAccent = Color(0xFF111113),
    iconDisabled = Color(0xFF48484A),
    borderDefault = Color(0xFF48484A),
    borderStrong = Color(0xFF8E8E93),
    borderFocus = Color(0xFFFDD501),
    borderError = Color(0xFFF87171),
    separatorDefault = Color(0xFF3A3A3C),
    shadowDefault = Color(0x66000000),
    shadowNone = Color(0x00000000),
    surfaceScreen = Color(0xFF000000),
    shadowElevation1 = Color(0x66000000),
    fillOnAccent = Color(0xFF111113),
    fillAccentSubtle = Color(0xFF724009),
    fillTransparent = Color(0x00000000),
    componentSpecificListItemFill = Color(0xFF000000),
    componentSpecificTopAppBarFill = Color(0xFF000000),
    componentSpecificToggleThumbOff = Color(0xFF8E8E93),
    componentSpecificToggleTrackBorderColor = Color(0xFF8E8E93),
    componentSpecificToggleThumbOn = Color(0xFF111113),
    componentSpecificSegmentedControlTrack = Color(0x00000000),
    componentSpecificSegmentedControlSelectedFill = Color(0xFF724009),
    componentSpecificTextFieldFill = Color(0x00000000),
)

object Spacing {
    val ScreenMargin = 16.dp // OS::Spacing/Screen Margin
    val Stack = 8.dp // OS::Spacing/Stack Gap
    val Inline = 16.dp // OS::Spacing/Inline Gap
    val Section = 24.dp // OS::Spacing/Section Gap
    val Tight = 2.dp // OS::Spacing/Tight
    val ButtonX = 24.dp // Component Specific::Button/Padding X
    val ListItemX = 16.dp // Component Specific::List Item/Padding X
    val ListItemY = 12.dp // Component Specific::List Item/Padding Y
    val ListInset = 0.dp // Component Specific::List Group/Inset
    val FieldX = 16.dp // Component Specific::Text Field/Padding X
}

object Os {
    val RadiusCard = 12.dp // OS::Radius/Card
    val RadiusFull = 999.dp // OS::Radius/Full
}

object Opacity {
    val StateDisabledOpacity = 0.38f // OS::State/Disabled Opacity
}

object ComponentSpecific {
    val ButtonHeight = 40.dp // Component Specific::Button/Height
    val ButtonRadius = 999.dp // Component Specific::Button/Radius
    val IconButtonSize = 48.dp // Component Specific::Icon Button/Size
    val ListItemMinHeight = 56.dp // Component Specific::List Item/Min Height
    val ListGroupRadius = 0.dp // Component Specific::List Group/Radius
    val TextFieldHeight = 56.dp // Component Specific::Text Field/Height
    val TextFieldRadius = 4.dp // Component Specific::Text Field/Radius
    val TextFieldLabelPadding = 4.dp // Component Specific::Text Field/Label Padding
    val TopAppBarHeight = 64.dp // Component Specific::Top App Bar/Height
    val TopAppBarPaddingX = 4.dp // Component Specific::Top App Bar/Padding X
    val TopAppBarTitleInset = 12.dp // Component Specific::Top App Bar/Title Inset
    val SegmentedControlRadiusOuter = 999.dp // Component Specific::Segmented Control/Radius Outer
    val SegmentedControlRadiusInner = 0.dp // Component Specific::Segmented Control/Radius Inner
    val SegmentedControlHeight = 40.dp // Component Specific::Segmented Control/Height
    val SegmentedControlPadding = 0.dp // Component Specific::Segmented Control/Padding
    val ToggleTrackWidth = 52.dp // Component Specific::Toggle/Track Width
    val ToggleTrackHeight = 32.dp // Component Specific::Toggle/Track Height
    val ToggleThumbSizeOff = 16.dp // Component Specific::Toggle/Thumb Size Off
    val ToggleThumbSizeOn = 24.dp // Component Specific::Toggle/Thumb Size On
    val ToggleTrackBorder = 2.dp // Component Specific::Toggle/Track Border
    val ToggleThumbInsetOff = 8.dp // Component Specific::Toggle/Thumb Inset Off
    val ToggleThumbInsetOn = 4.dp // Component Specific::Toggle/Thumb Inset On
    val SegmentedControlBorder = 1.dp // Component Specific::Segmented Control/Border
    val CheckboxGlyph = 18.dp // Component Specific::Checkbox/Glyph
    val CheckboxSize = 18.dp // Component Specific::Checkbox/Size
    val CheckboxRadius = 2.dp // Component Specific::Checkbox/Radius
    val CheckboxBorder = 2.dp // Component Specific::Checkbox/Border
    val TextFieldBorder = 1.dp // Component Specific::Text Field/Border
    val TextFieldBorderFocused = 2.dp // Component Specific::Text Field/Border Focused
    val TextFieldLabelInset = 12.dp // Component Specific::Text Field/Label Inset
}

object Size {
    val Icon = 24.dp // Component Specific::Icon/Size
}

/** Text styles resolved for Android, per Language mode. Prefer MaterialTheme.typography.* (see Storybook). */
object AppTypography {
    val largeTitle = TextStyle(fontSize = 24.sp, lineHeight = 32.sp, fontWeight = FontWeight(400)) // Roboto
    val largeTitleAr = TextStyle(fontSize = 24.sp, lineHeight = 36.sp, fontWeight = FontWeight(400)) // Noto Sans Arabic
    val title = TextStyle(fontSize = 22.sp, lineHeight = 28.sp, fontWeight = FontWeight(400)) // Roboto
    val titleAr = TextStyle(fontSize = 22.sp, lineHeight = 32.sp, fontWeight = FontWeight(400)) // Noto Sans Arabic
    val headline = TextStyle(fontSize = 16.sp, lineHeight = 24.sp, fontWeight = FontWeight(500)) // Roboto
    val headlineAr = TextStyle(fontSize = 16.sp, lineHeight = 24.sp, fontWeight = FontWeight(500)) // Noto Sans Arabic
    val body = TextStyle(fontSize = 16.sp, lineHeight = 24.sp, fontWeight = FontWeight(400)) // Roboto
    val bodyAr = TextStyle(fontSize = 16.sp, lineHeight = 24.sp, fontWeight = FontWeight(400)) // Noto Sans Arabic
    val subhead = TextStyle(fontSize = 14.sp, lineHeight = 20.sp, fontWeight = FontWeight(400)) // Roboto
    val subheadAr = TextStyle(fontSize = 14.sp, lineHeight = 20.sp, fontWeight = FontWeight(400)) // Noto Sans Arabic
    val footnote = TextStyle(fontSize = 12.sp, lineHeight = 16.sp, fontWeight = FontWeight(400)) // Roboto
    val footnoteAr = TextStyle(fontSize = 12.sp, lineHeight = 18.sp, fontWeight = FontWeight(400)) // Noto Sans Arabic
    val caption = TextStyle(fontSize = 11.sp, lineHeight = 16.sp, fontWeight = FontWeight(500)) // Roboto
    val captionAr = TextStyle(fontSize = 11.sp, lineHeight = 16.sp, fontWeight = FontWeight(500)) // Noto Sans Arabic
    val buttonLabel = TextStyle(fontSize = 14.sp, lineHeight = 20.sp, fontWeight = FontWeight(500)) // Roboto
    val buttonLabelAr = TextStyle(fontSize = 14.sp, lineHeight = 20.sp, fontWeight = FontWeight(500)) // Noto Sans Arabic
}

