// DesignTokens.swift - Native One File Pilot design tokens for SwiftUI (OS mode: iOS).
// Generated by tools/tokens_to_css.py from data/tokens.json (Figma variables). Do not edit by hand.
// Names in Storybook are the Figma Code syntax; the enums below declare the ones that are app tokens
// (Spacing.screenMargin, Toggle.trackWidth...), so that code compiles. System APIs (Color(.label), .font(.body))
// are used as they are. Colors adapt to Light/Dark automatically.
import SwiftUI
import UIKit

extension Color {
    init(hex: UInt32) {
        self.init(.sRGB, red: Double((hex >> 24) & 0xFF) / 255, green: Double((hex >> 16) & 0xFF) / 255,
                  blue: Double((hex >> 8) & 0xFF) / 255, opacity: Double(hex & 0xFF) / 255)
    }
    init(light: UInt32, dark: UInt32) {
        self.init(UIColor { $0.userInterfaceStyle == .dark ? UIColor(Color(hex: dark)) : UIColor(Color(hex: light)) })
    }

    static let backgroundPrimary = Color(light: 0xFFFFFFFF, dark: 0x000000FF) // Color::Background/Primary · Figma: Color(.systemBackground)
    static let backgroundGrouped = Color(light: 0xF2F2F7FF, dark: 0x000000FF) // Color::Background/Grouped · Figma: Color(.systemGroupedBackground)
    static let backgroundElevated = Color(light: 0xFFFFFFFF, dark: 0x1C1C1EFF) // Color::Background/Elevated · Figma: Color(.secondarySystemGroupedBackground)
    static let surfaceContainer = Color(light: 0xF2F2F7FF, dark: 0x1C1C1EFF) // Color::Surface/Container · Figma: Color(.secondarySystemBackground)
    static let surfaceContainerHigh = Color(light: 0xE5E5EAFF, dark: 0x2C2C2EFF) // Color::Surface/Container High · Figma: Color(.tertiarySystemBackground)
    static let labelPrimary = Color(light: 0x000000FF, dark: 0xFFFFFFFF) // Color::Label/Primary · Figma: Color(.label)
    static let labelSecondary = Color(light: 0x636366FF, dark: 0xAEAEB2FF) // Color::Label/Secondary · Figma: Color(.secondaryLabel)
    static let labelTertiary = Color(light: 0x8E8E93FF, dark: 0x8E8E93FF) // Color::Label/Tertiary · Figma: Color(.tertiaryLabel)
    static let labelDisabled = Color(light: 0xC7C7CCFF, dark: 0x48484AFF) // Color::Label/Disabled · Figma: Color(.quaternaryLabel)
    static let labelOnAccent = Color(light: 0x111113FF, dark: 0x111113FF) // Color::Label/On Accent · Figma: Color("OnAccent")
    static let labelAccent = Color(light: 0xA36600FF, dark: 0xFDD501FF) // Color::Label/Accent · Figma: Color.accentColor
    static let labelError = Color(light: 0xB91C1CFF, dark: 0xF87171FF) // Color::Label/Error · Figma: Color(.systemRed)
    static let fillAccent = Color(light: 0xFDD501FF, dark: 0xFDD501FF) // Color::Fill/Accent · Figma: Color("AccentFill")
    static let fillAccentPressed = Color(light: 0xECBB00FF, dark: 0xFDE744FF) // Color::Fill/Accent Pressed · Figma: Color("AccentFillPressed")
    static let fillSecondary = Color(light: 0xE5E5EAFF, dark: 0x2C2C2EFF) // Color::Fill/Secondary · Figma: Color(.secondarySystemFill)
    static let fillSecondaryPressed = Color(light: 0xD1D1D6FF, dark: 0x3A3A3CFF) // Color::Fill/Secondary Pressed · Figma: Color(.systemFill)
    static let fillDisabled = Color(light: 0xE5E5EAFF, dark: 0x2C2C2EFF) // Color::Fill/Disabled · Figma: Color(.quaternarySystemFill)
    static let fillTrackOff = Color(light: 0xE5E5EAFF, dark: 0x3A3A3CFF) // Color::Fill/Track Off · Figma: Color(.systemFill)
    static let fillThumb = Color(light: 0xFFFFFFFF, dark: 0xFFFFFFFF) // Color::Fill/Thumb · Figma: Color.white
    static let fillThumbOff = Color(light: 0x8E8E93FF, dark: 0x8E8E93FF) // Color::Fill/Thumb Off · Figma: Color.white
    static let fillSegmentSelected = Color(light: 0xFFFFFFFF, dark: 0x48484AFF) // Color::Fill/Segment Selected · Figma: Color(.systemBackground)
    static let iconPrimary = Color(light: 0x000000FF, dark: 0xFFFFFFFF) // Color::Icon/Primary · Figma: Color(.label)
    static let iconSecondary = Color(light: 0x8E8E93FF, dark: 0x8E8E93FF) // Color::Icon/Secondary · Figma: Color(.secondaryLabel)
    static let iconAccent = Color(light: 0xA36600FF, dark: 0xFDD501FF) // Color::Icon/Accent · Figma: Color.accentColor
    static let iconOnAccent = Color(light: 0x111113FF, dark: 0x111113FF) // Color::Icon/On Accent · Figma: Color("OnAccent")
    static let iconDisabled = Color(light: 0xC7C7CCFF, dark: 0x48484AFF) // Color::Icon/Disabled · Figma: Color(.quaternaryLabel)
    static let borderDefault = Color(light: 0xD1D1D6FF, dark: 0x48484AFF) // Color::Border/Default · Figma: Color(.separator)
    static let borderStrong = Color(light: 0x8E8E93FF, dark: 0x8E8E93FF) // Color::Border/Strong · Figma: Color(.opaqueSeparator)
    static let borderFocus = Color(light: 0xA36600FF, dark: 0xFDD501FF) // Color::Border/Focus · Figma: Color.accentColor
    static let borderError = Color(light: 0xDC2626FF, dark: 0xF87171FF) // Color::Border/Error · Figma: Color(.systemRed)
    static let separatorDefault = Color(light: 0xD1D1D6FF, dark: 0x3A3A3CFF) // Color::Separator/Default · Figma: Color(.separator)
    static let shadowDefault = Color(light: 0x00000033, dark: 0x00000066) // Color::Shadow/Default · Figma: Color.black.opacity(0.2)
    static let shadowNone = Color(light: 0x00000000, dark: 0x00000000) // Color::Shadow/None · Figma: Color.clear
    static let surfaceScreen = Color(light: 0xF2F2F7FF, dark: 0x000000FF) // OS::Surface/Screen · Figma: Color(.systemGroupedBackground)
    static let shadowElevation1 = Color(light: 0x00000000, dark: 0x00000000) // OS::Shadow/Elevation 1 · Figma: Color.clear
    static let fillOnAccent = Color(light: 0x111113FF, dark: 0x111113FF) // Color::Fill/On Accent · Figma: Color("OnAccent")
    static let fillAccentSubtle = Color(light: 0xFDFCC3FF, dark: 0x724009FF) // Color::Fill/Accent Subtle · Figma: Color.accentColor.opacity(0.15)
    static let fillTransparent = Color(light: 0x00000000, dark: 0x00000000) // Color::Fill/Transparent · Figma: Color.clear
    static let componentSpecificListItemFill = Color(light: 0xFFFFFFFF, dark: 0x1C1C1EFF) // Component Specific::List Item/Fill · Figma: Color(.secondarySystemGroupedBackground)
    static let componentSpecificTopAppBarFill = Color(light: 0xF2F2F7FF, dark: 0x000000FF) // Component Specific::Top App Bar/Fill · Figma: Color(.systemGroupedBackground)
    static let componentSpecificToggleThumbOff = Color(light: 0xFFFFFFFF, dark: 0xFFFFFFFF) // Component Specific::Toggle/Thumb Off · Figma: Color.white
    static let componentSpecificToggleTrackBorderColor = Color(light: 0x00000000, dark: 0x00000000) // Component Specific::Toggle/Track Border Color · Figma: Color.clear
    static let componentSpecificToggleThumbOn = Color(light: 0xFFFFFFFF, dark: 0xFFFFFFFF) // Component Specific::Toggle/Thumb On · Figma: Color.white
    static let componentSpecificSegmentedControlTrack = Color(light: 0xE5E5EAFF, dark: 0x2C2C2EFF) // Component Specific::Segmented Control/Track · Figma: Color(.secondarySystemFill)
    static let componentSpecificSegmentedControlSelectedFill = Color(light: 0xFFFFFFFF, dark: 0x48484AFF) // Component Specific::Segmented Control/Selected Fill · Figma: Color(.systemBackground)
    static let componentSpecificTextFieldFill = Color(light: 0xE5E5EAFF, dark: 0x2C2C2EFF) // Component Specific::Text Field/Fill · Figma: Color(.secondarySystemFill)
}

enum Spacing {
    static let screenMargin: CGFloat = 16 // OS::Spacing/Screen Margin
    static let stack: CGFloat = 8 // OS::Spacing/Stack Gap
    static let inline: CGFloat = 12 // OS::Spacing/Inline Gap
    static let section: CGFloat = 35 // OS::Spacing/Section Gap
    static let tight: CGFloat = 2 // OS::Spacing/Tight
    static let buttonX: CGFloat = 20 // Component Specific::Button/Padding X
    static let listItemX: CGFloat = 16 // Component Specific::List Item/Padding X
    static let listItemY: CGFloat = 11 // Component Specific::List Item/Padding Y
    static let listInset: CGFloat = 16 // Component Specific::List Group/Inset
    static let fieldX: CGFloat = 16 // Component Specific::Text Field/Padding X
    static let labelPadding: CGFloat = 4 // Component Specific::Text Field/Label Padding
    static let barX: CGFloat = 8 // Component Specific::Top App Bar/Padding X
    static let barTitleInset: CGFloat = 0 // Component Specific::Top App Bar/Title Inset
}

enum Radius {
    static let card: CGFloat = 10 // OS::Radius/Card
    static let button: CGFloat = 12 // Component Specific::Button/Radius
    static let listGroup: CGFloat = 10 // Component Specific::List Group/Radius
    static let field: CGFloat = 10 // Component Specific::Text Field/Radius
}

enum Os {
    static let radiusFull: CGFloat = 999 // OS::Radius/Full
}

enum Opacity {
    static let stateDisabledOpacity: Double = 0.4 // OS::State/Disabled Opacity
}

enum Size {
    static let button: CGFloat = 50 // Component Specific::Button/Height
    static let iconButton: CGFloat = 44 // Component Specific::Icon Button/Size
    static let icon: CGFloat = 22 // Component Specific::Icon/Size
    static let listItem: CGFloat = 44 // Component Specific::List Item/Min Height
    static let textField: CGFloat = 44 // Component Specific::Text Field/Height
    static let navigationBar: CGFloat = 44 // Component Specific::Top App Bar/Height
}

enum SegmentedControl {
    static let radiusOuter: CGFloat = 9 // Component Specific::Segmented Control/Radius Outer
    static let radiusInner: CGFloat = 7 // Component Specific::Segmented Control/Radius Inner
    static let height: CGFloat = 32 // Component Specific::Segmented Control/Height
    static let padding: CGFloat = 2 // Component Specific::Segmented Control/Padding
    static let border: CGFloat = 0 // Component Specific::Segmented Control/Border
}

enum Toggle {
    static let trackWidth: CGFloat = 51 // Component Specific::Toggle/Track Width
    static let trackHeight: CGFloat = 31 // Component Specific::Toggle/Track Height
    static let thumbOff: CGFloat = 27 // Component Specific::Toggle/Thumb Size Off
    static let thumbOn: CGFloat = 27 // Component Specific::Toggle/Thumb Size On
    static let trackBorder: CGFloat = 0 // Component Specific::Toggle/Track Border
    static let thumbInset: CGFloat = 2 // Component Specific::Toggle/Thumb Inset Off
}

enum Checkbox {
    static let glyph: CGFloat = 16 // Component Specific::Checkbox/Glyph
    static let size: CGFloat = 22 // Component Specific::Checkbox/Size
    static let radius: CGFloat = 999 // Component Specific::Checkbox/Radius
    static let border: CGFloat = 1.5 // Component Specific::Checkbox/Border
}

enum TextField {
    static let border: CGFloat = 0 // Component Specific::Text Field/Border
    static let borderFocused: CGFloat = 0 // Component Specific::Text Field/Border Focused
    static let labelInset: CGFloat = 12 // Component Specific::Text Field/Label Inset
}

struct TypeSpec { let size: CGFloat; let lineHeight: CGFloat; let weight: Font.Weight; let family: String }

/// Text styles resolved for iOS, per Language mode. Prefer the Dynamic Type style in Storybook (.font(.body)).
enum TypeScale {
    static let largeTitle = TypeSpec(size: 34, lineHeight: 41, weight: .bold, family: "SF Pro")
    static let largeTitleAr = TypeSpec(size: 34, lineHeight: 52, weight: .bold, family: "Noto Sans Arabic")
    static let title = TypeSpec(size: 22, lineHeight: 28, weight: .bold, family: "SF Pro")
    static let titleAr = TypeSpec(size: 22, lineHeight: 32, weight: .bold, family: "Noto Sans Arabic")
    static let headline = TypeSpec(size: 17, lineHeight: 22, weight: .semibold, family: "SF Pro")
    static let headlineAr = TypeSpec(size: 17, lineHeight: 26, weight: .semibold, family: "Noto Sans Arabic")
    static let body = TypeSpec(size: 17, lineHeight: 22, weight: .regular, family: "SF Pro")
    static let bodyAr = TypeSpec(size: 17, lineHeight: 26, weight: .regular, family: "Noto Sans Arabic")
    static let subhead = TypeSpec(size: 15, lineHeight: 20, weight: .regular, family: "SF Pro")
    static let subheadAr = TypeSpec(size: 15, lineHeight: 22, weight: .regular, family: "Noto Sans Arabic")
    static let footnote = TypeSpec(size: 13, lineHeight: 18, weight: .regular, family: "SF Pro")
    static let footnoteAr = TypeSpec(size: 13, lineHeight: 20, weight: .regular, family: "Noto Sans Arabic")
    static let caption = TypeSpec(size: 12, lineHeight: 16, weight: .regular, family: "SF Pro")
    static let captionAr = TypeSpec(size: 12, lineHeight: 18, weight: .regular, family: "Noto Sans Arabic")
    static let buttonLabel = TypeSpec(size: 17, lineHeight: 22, weight: .semibold, family: "SF Pro")
    static let buttonLabelAr = TypeSpec(size: 17, lineHeight: 26, weight: .semibold, family: "Noto Sans Arabic")
}

