// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Checkbox } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Checkbox",
  component: Checkbox,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Value": {
    "control": "inline-radio",
    "options": [
      "Checked",
      "Unchecked"
    ],
    "description": "Figma variant property `Value`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Checked"
      }
    }
  },
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  }
},
  args: {"Value": "Checked", "State": "Default"},
  parameters: {
    figma: { name: "Checkbox", page: "➜ Checkbox", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=4-15524" },
    docs: { description: { component: "**Figma:** `Checkbox` on page `➜ Checkbox` (Form Elements). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=4-15524)\n\n**Tier:** Atom\n\n**Use:** Selects one or more items from a list, or confirms an option before submitting.\n\n**Figma description:**\n\n> Purpose: Selects one or more items from a list, or confirms an option before submitting.  \n> Usage Rules: Use for multi-select and for options confirmed by a later action; use Toggle for settings that apply at once and Radio (2-6 options) or Select (7+) for single choice. Label lives in the List Item title.  \n> Accessibility: Touch target comes from the List Item row (44 iOS / 48 Android); the box itself is 22 / 18. Check glyph on the yellow fill uses Icon/On Accent (14.7:1). Unchecked border uses Border/Strong (3:1+ on surfaces).  \n\n**Built from:** `Icon/Check`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Checked: Story = { name: "Checked", args: { "Value": "Checked" } };
export const Unchecked: Story = { name: "Unchecked", args: { "Value": "Unchecked" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Checkbox {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Checked", "Unchecked"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Value={x}</div>
          <div className="sb-row">{["Default", "Disabled"].map((y) => <Checkbox key={y} {...args} {...{ "Value": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
