// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { TextField } from '../../components/FormElements';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Form Elements/Text Field",
  component: TextField,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Focused",
      "Error",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Display name"
      }
    }
  },
  "Value": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Abdul"
      }
    }
  },
  "Helper Text": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Shown on your profile"
      }
    }
  },
  "Show Helper Text": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Leading Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Leading Icon Swap": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Person"
      }
    }
  },
  "Trailing Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Trailing Icon Swap": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Close"
      }
    }
  }
},
  args: {"State": "Default", "Label": "Display name", "Value": "Abdul", "Helper Text": "Shown on your profile", "Show Helper Text": true, "Leading Icon": false, "Leading Icon Swap": "Icon/Person", "Trailing Icon": true, "Trailing Icon Swap": "Icon/Close"},
  parameters: {
    figma: { name: "Text Field", page: "➜ Text Field", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-28190" },
    docs: { description: { component: "**Figma:** `Text Field` on page `➜ Text Field` (Form Elements). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=9-28190)\n\n**Tier:** Molecule\n\n**Use:** Single-line text entry in forms and settings (names, email, search terms).\n\n**Figma description:**\n\n> Purpose: Single-line text entry in forms and settings (names, email, search terms).  \n> Usage Rules: Always set Label (it shows above the field on iOS and on the border on Android: never use placeholder as the label). Helper Text explains format; Error state replaces it with the error message. Trailing Close clears the value. Use Select for 7+ fixed options, Radio for 2-6. RTL (Language AR) mirrors icons and aligns text to the right automatically.  \n> Accessibility: Height 44 iOS / 56 Android (meets touch targets). Label and helper text use Label/Secondary (4.5:1+). Error is shown by text and border color, not color alone. Android floating label background follows Surface/Screen; place the field on that surface.  \n\n**Built from:** `Icon/Person`, `Icon/Close`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof TextField>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Focused: Story = { name: "Focused", args: { "State": "Focused" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Focused", "Error", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <TextField {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Focused", "Error", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <TextField {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
