// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Toggle } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Toggle",
  component: Toggle,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Value": {
    "control": "inline-radio",
    "options": [
      "On",
      "Off"
    ],
    "description": "Figma variant property `Value`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "On"
      }
    }
  },
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  }
},
  args: {"Value": "On", "State": "Default"},
  parameters: {
    figma: { name: "Toggle", page: "➜ Toggle", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=4-15484" },
    docs: { description: { component: "**Figma:** `Toggle` on page `➜ Toggle` (Form Elements). [Open in Figma](https://www.figma.com/design/a2EAdCeKeaXN679TMNlIev/Native-One-File-Pilot-Design-System?node-id=4-15484)\n\n**Tier:** Atom\n\n**Use:** Turns a single setting on or off with immediate effect.\n\n**Figma description:**\n\n> Purpose: Turns a single setting on or off with immediate effect.  \n> Usage Rules: Use in List Item trailing for settings that apply at once; use Checkbox for choices confirmed later or for multi-select. Never pair with a Save button. Label lives in the List Item title, not inside the toggle.  \n> Accessibility: Track meets the touch target only inside a List Item (44 iOS / 48 Android row). The yellow On track against white is 1.4:1, below the 3:1 non-text contrast guideline: state is also shown by thumb position, and Android adds a dark thumb (Fill/On Accent). Disabled uses State/Disabled Opacity.  \n\nControls use the Figma variant and property names exactly. Switch the Figma modes from the toolbar (Platform = the OS mode iOS / Android, Color, Language)." } },
  },
} satisfies Meta<typeof Toggle>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const On: Story = { name: "On", args: { "Value": "On" } };
export const Off: Story = { name: "Off", args: { "Value": "Off" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Toggle {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["On", "Off"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Value={x}</div>
          <div className="sb-row">{["Default", "Disabled"].map((y) => <Toggle key={y} {...args} {...{ "Value": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
